plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme-DEV

url: https://ucsb-cs56.github.io # the base hostname & protocol for your site
baseurl: /s19  # the subpath of your site, e.g. "/blog"

course: "CS56"
qtr: "S19"
qxx: "s19"
quarter: "Spring 2019"
piazza_url: https://piazza.com/class/to-be-determined
gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=to-be-determined
github_org_name: ucsb-cs56-s19
github_org_url: https://github.com/ucsb-cs56-s19

ta_list: "TBD and TBD"
ta_list_full: "FirstTA LastName and SecondTA Lastname"
mentors_list: "Mentor1, Mentor2, Mentor3 and Mentor4"
discussion_section_times: "5pm,&nbsp;6pm,&nbsp;7pm"

github_url: https://github.com/ucsb-cs56/s19
mentor_url: https://ucsb-cs56-pconrad-mentors.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048
hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 

legacy_wiki_url: https://foo.cs.ucsb.edu/56wiki
legacy_wiki_name: "56wiki"

submit_cs_course: TBD

start_week: 1
start_date: 2019-03-31 00:00:00.00-8:00
num_weeks: 10
extra_exam_week: true
sections: "5pm,&nbsp;6pm,&nbsp;7pm"

cal_dates: >
  [
    {"label":"S19 official start date", "date":"2019-09-23" },
    {"label":"S19 1st day of instruction", "date":"2019-09-27" },	
    {"label":"Univ Holiday", "date":"2019-05-27" },
    {"label":"S19 instruction ends", "date":"2019-06-07" },
    {"label":"S19 finals start", "date":"2019-06-08" },
    {"label":"S19 finals end", "date":"2019-06-14" },
    {"label":"S19 qtr ends", "date":"2019-06-14" }
  ]

hwk_drop_lowest: three

legacy_wiki_name: 56wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/56wiki" 


hfj_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfj/HFJ_Chapter_"
hfdp_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfdp/HFDP_Chapter_"

kramdown:
   parse_block_html: true


exclude:
   - vendor
   - _exam/e02/cs56_m16_e02/code
   - _exam/e01/cs56_f16_e01/code


timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
    print: true
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
    print: true
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff

head_scripts:
   - /static/js/select_section.js
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

include:
  - _pages
exclude: [vendor]
